export const FETCH_POSTALLOOKUP_REQUEST = 'FETCH_POSTALLOOKUP_REQUEST'
export const FETCH_POSTALLOOKUP_SUCCESS = 'FETCH_POSTALLOOKUP_SUCCESS'
export const FETCH_POSTALLOOKUP_FAILURE = 'FETCH_POSTALLOOKUP_FAILURE'